//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Content {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Content() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Content", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        internal static string birthDay {
            get {
                return ResourceManager.GetString("birthDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Result.
        /// </summary>
        internal static string checkResult {
            get {
                return ResourceManager.GetString("checkResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string detail {
            get {
                return ResourceManager.GetString("detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops.
        /// </summary>
        internal static string errorPage1 {
            get {
                return ResourceManager.GetString("errorPage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page you are looking for not avaible!.
        /// </summary>
        internal static string errorPage2 {
            get {
                return ResourceManager.GetString("errorPage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculty.
        /// </summary>
        internal static string faculty {
            get {
                return ResourceManager.GetString("faculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculty ID.
        /// </summary>
        internal static string facultyId {
            get {
                return ResourceManager.GetString("facultyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculty List.
        /// </summary>
        internal static string facultyList {
            get {
                return ResourceManager.GetString("facultyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculty Name.
        /// </summary>
        internal static string facultyName {
            get {
                return ResourceManager.GetString("facultyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string fullName {
            get {
                return ResourceManager.GetString("fullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string gender {
            get {
                return ResourceManager.GetString("gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        internal static string hello {
            get {
                return ResourceManager.GetString("hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are logged in or do not have permission to access this page. Please come back.
        /// </summary>
        internal static string messageIsLogin {
            get {
                return ResourceManager.GetString("messageIsLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of lessons.
        /// </summary>
        internal static string numberLessons {
            get {
                return ResourceManager.GetString("numberLessons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string result {
            get {
                return ResourceManager.GetString("result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result for student.
        /// </summary>
        internal static string resultForStudent {
            get {
                return ResourceManager.GetString("resultForStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result List.
        /// </summary>
        internal static string resultList {
            get {
                return ResourceManager.GetString("resultList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of results in.
        /// </summary>
        internal static string resultListForSubject {
            get {
                return ResourceManager.GetString("resultListForSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        internal static string score {
            get {
                return ResourceManager.GetString("score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        internal static string student {
            get {
                return ResourceManager.GetString("student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student ID.
        /// </summary>
        internal static string studentId {
            get {
                return ResourceManager.GetString("studentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student List.
        /// </summary>
        internal static string studentList {
            get {
                return ResourceManager.GetString("studentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of students by faculty.
        /// </summary>
        internal static string studentListForFaculty {
            get {
                return ResourceManager.GetString("studentListForFaculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string subject {
            get {
                return ResourceManager.GetString("subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject ID.
        /// </summary>
        internal static string subjectId {
            get {
                return ResourceManager.GetString("subjectId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject List.
        /// </summary>
        internal static string subjectList {
            get {
                return ResourceManager.GetString("subjectList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject Name.
        /// </summary>
        internal static string subjectName {
            get {
                return ResourceManager.GetString("subjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student management system.
        /// </summary>
        internal static string systemManagementStudent {
            get {
                return ResourceManager.GetString("systemManagementStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher.
        /// </summary>
        internal static string teacher {
            get {
                return ResourceManager.GetString("teacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher ID.
        /// </summary>
        internal static string teacherId {
            get {
                return ResourceManager.GetString("teacherId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher List.
        /// </summary>
        internal static string teacherList {
            get {
                return ResourceManager.GetString("teacherList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnamese.
        /// </summary>
        internal static string vietnamese {
            get {
                return ResourceManager.GetString("vietnamese", resourceCulture);
            }
        }
    }
}
