//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _51800882_51800187_QLSinhVien.Res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LangResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_51800882_51800187_QLSinhVien.Res.LangResource", typeof(LangResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        public static string birthDay {
            get {
                return ResourceManager.GetString("birthDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Result.
        /// </summary>
        public static string checkResult {
            get {
                return ResourceManager.GetString("checkResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string detail {
            get {
                return ResourceManager.GetString("detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops.
        /// </summary>
        public static string errorPage1 {
            get {
                return ResourceManager.GetString("errorPage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page you are looking for not avaible!.
        /// </summary>
        public static string errorPage2 {
            get {
                return ResourceManager.GetString("errorPage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculty.
        /// </summary>
        public static string faculty {
            get {
                return ResourceManager.GetString("faculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculty ID.
        /// </summary>
        public static string facultyId {
            get {
                return ResourceManager.GetString("facultyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculty List.
        /// </summary>
        public static string facultyList {
            get {
                return ResourceManager.GetString("facultyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculty Name.
        /// </summary>
        public static string facultyName {
            get {
                return ResourceManager.GetString("facultyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string fullName {
            get {
                return ResourceManager.GetString("fullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string gender {
            get {
                return ResourceManager.GetString("gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string hello {
            get {
                return ResourceManager.GetString("hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are logged in or do not have permission to access this page. Please come back.
        /// </summary>
        public static string messageIsLogin {
            get {
                return ResourceManager.GetString("messageIsLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you from the future?.
        /// </summary>
        public static string messDateValidationAttribute {
            get {
                return ResourceManager.GetString("messDateValidationAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete.
        /// </summary>
        public static string messDeleteError {
            get {
                return ResourceManager.GetString("messDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . Please try again when the Faculty has no Students!!!.
        /// </summary>
        public static string messDeleteErrorFaculty {
            get {
                return ResourceManager.GetString("messDeleteErrorFaculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted.
        /// </summary>
        public static string messDeleteSuccess {
            get {
                return ResourceManager.GetString("messDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong username or password.
        /// </summary>
        public static string messErrorLogin {
            get {
                return ResourceManager.GetString("messErrorLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculty ID already exists.
        /// </summary>
        public static string messExistsFacultyID {
            get {
                return ResourceManager.GetString("messExistsFacultyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student ID already exists.
        /// </summary>
        public static string messExistsStudentID {
            get {
                return ResourceManager.GetString("messExistsStudentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject ID already exists.
        /// </summary>
        public static string messExistsSubjectID {
            get {
                return ResourceManager.GetString("messExistsSubjectID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher ID already exists.
        /// </summary>
        public static string messExistsTeacherID {
            get {
                return ResourceManager.GetString("messExistsTeacherID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure delete.
        /// </summary>
        public static string messQuestionDelete {
            get {
                return ResourceManager.GetString("messQuestionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Birthday.
        /// </summary>
        public static string messRequiredBirthday {
            get {
                return ResourceManager.GetString("messRequiredBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Faculty.
        /// </summary>
        public static string messRequiredFaculty {
            get {
                return ResourceManager.GetString("messRequiredFaculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Faculty ID.
        /// </summary>
        public static string messRequiredFacultyId {
            get {
                return ResourceManager.GetString("messRequiredFacultyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Faculty Name.
        /// </summary>
        public static string messRequiredFacultyName {
            get {
                return ResourceManager.GetString("messRequiredFacultyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Full Name.
        /// </summary>
        public static string messRequiredFullName {
            get {
                return ResourceManager.GetString("messRequiredFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Gender.
        /// </summary>
        public static string messRequiredGender {
            get {
                return ResourceManager.GetString("messRequiredGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the number of lessons.
        /// </summary>
        public static string messRequiredNumberLess {
            get {
                return ResourceManager.GetString("messRequiredNumberLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a password.
        /// </summary>
        public static string messRequiredPassword {
            get {
                return ResourceManager.GetString("messRequiredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Score.
        /// </summary>
        public static string messRequiredScore {
            get {
                return ResourceManager.GetString("messRequiredScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Student.
        /// </summary>
        public static string messRequiredStudent {
            get {
                return ResourceManager.GetString("messRequiredStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the Student ID.
        /// </summary>
        public static string messRequiredStudentId {
            get {
                return ResourceManager.GetString("messRequiredStudentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Subject.
        /// </summary>
        public static string messRequiredSubject {
            get {
                return ResourceManager.GetString("messRequiredSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Subject ID.
        /// </summary>
        public static string messRequiredSubjectId {
            get {
                return ResourceManager.GetString("messRequiredSubjectId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Subject Name.
        /// </summary>
        public static string messRequiredSubjectName {
            get {
                return ResourceManager.GetString("messRequiredSubjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Teacher ID.
        /// </summary>
        public static string messRequiredTeacherId {
            get {
                return ResourceManager.GetString("messRequiredTeacherId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Username.
        /// </summary>
        public static string messRequiredUsername {
            get {
                return ResourceManager.GetString("messRequiredUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculty ID does not exceed 5 characters.
        /// </summary>
        public static string messStringFacultyId {
            get {
                return ResourceManager.GetString("messStringFacultyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculty Name must not exceed 100 characters.
        /// </summary>
        public static string messStringFacultyName {
            get {
                return ResourceManager.GetString("messStringFacultyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name must not exceed 100 characters.
        /// </summary>
        public static string messStringFullName {
            get {
                return ResourceManager.GetString("messStringFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of lessons must be greater than 0.
        /// </summary>
        public static string messStringNumberLess {
            get {
                return ResourceManager.GetString("messStringNumberLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must not exceed 50 characters.
        /// </summary>
        public static string messStringPassword {
            get {
                return ResourceManager.GetString("messStringPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score from 0 - 10.
        /// </summary>
        public static string messStringScore {
            get {
                return ResourceManager.GetString("messStringScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student ID should not exceed 5 characters.
        /// </summary>
        public static string messStringStudentId {
            get {
                return ResourceManager.GetString("messStringStudentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject ID should not exceed 5 characters.
        /// </summary>
        public static string messStringSubjectId {
            get {
                return ResourceManager.GetString("messStringSubjectId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject Name should not exceed 100 characters.
        /// </summary>
        public static string messStringSubjectName {
            get {
                return ResourceManager.GetString("messStringSubjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher ID should not exceed 5 characters.
        /// </summary>
        public static string messStringTeacherId {
            get {
                return ResourceManager.GetString("messStringTeacherId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username must not exceed 50 characters.
        /// </summary>
        public static string messStringUsername {
            get {
                return ResourceManager.GetString("messStringUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of lessons.
        /// </summary>
        public static string numberLessons {
            get {
                return ResourceManager.GetString("numberLessons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string result {
            get {
                return ResourceManager.GetString("result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result for student.
        /// </summary>
        public static string resultForStudent {
            get {
                return ResourceManager.GetString("resultForStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result List.
        /// </summary>
        public static string resultList {
            get {
                return ResourceManager.GetString("resultList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of results in.
        /// </summary>
        public static string resultListForSubject {
            get {
                return ResourceManager.GetString("resultListForSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string roles {
            get {
                return ResourceManager.GetString("roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string score {
            get {
                return ResourceManager.GetString("score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        public static string student {
            get {
                return ResourceManager.GetString("student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student ID.
        /// </summary>
        public static string studentId {
            get {
                return ResourceManager.GetString("studentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student List.
        /// </summary>
        public static string studentList {
            get {
                return ResourceManager.GetString("studentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of students by faculty.
        /// </summary>
        public static string studentListForFaculty {
            get {
                return ResourceManager.GetString("studentListForFaculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string subject {
            get {
                return ResourceManager.GetString("subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject ID.
        /// </summary>
        public static string subjectId {
            get {
                return ResourceManager.GetString("subjectId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject List.
        /// </summary>
        public static string subjectList {
            get {
                return ResourceManager.GetString("subjectList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject Name.
        /// </summary>
        public static string subjectName {
            get {
                return ResourceManager.GetString("subjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student management system.
        /// </summary>
        public static string systemManagementStudent {
            get {
                return ResourceManager.GetString("systemManagementStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher.
        /// </summary>
        public static string teacher {
            get {
                return ResourceManager.GetString("teacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher ID.
        /// </summary>
        public static string teacherId {
            get {
                return ResourceManager.GetString("teacherId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher List.
        /// </summary>
        public static string teacherList {
            get {
                return ResourceManager.GetString("teacherList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User List.
        /// </summary>
        public static string userList {
            get {
                return ResourceManager.GetString("userList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnamese.
        /// </summary>
        public static string vietnamese {
            get {
                return ResourceManager.GetString("vietnamese", resourceCulture);
            }
        }
    }
}
